# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OSFA', models.CharField(max_length=500)),
                ('OSFB', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Proteinanno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genename', models.CharField(max_length=500)),
                ('genefunc', models.CharField(max_length=500)),
                ('genefunc_disc', models.CharField(max_length=100)),
            ],
        ),
    ]
