# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proteinanno',
            new_name='Panno',
        ),
        migrations.RenameModel(
            old_name='Pinteraction',
            new_name='Pinter',
        ),
    ]
